#!/bin/bash

# Selects all email account from `pass` and prepares mailboxes for them.
# Accounts should be stored with path like "email/name/login", where "name"
# is a logical account name, like "work" or "personal".
# Script takes a color name for account from the hardcoded list.

# $1 - default account name, account with this name will be activated at startup.

dft="$1"

colors=(
'magenta'
'green'
'yellow'
'red'
'cyan'
'blue'
)

c=0
sz=${#colors[@]}

for acc in $(pass ls -f -s email-and-im/google | cut -d/ -f1 | sort -u); do
  d=""
  if [ -z "$dft" ] || [ "$1" = "$acc" ]; then
    d="default"
    dft="$acc"
  fi
  echo "source \"~/.mutt/accounts/setup $acc ${colors[c % sz]} $d |\""
  c=$(( $c + 1 ))
done
