#!/bin/sh

set -v

# Installing GO packages into $GOPATH within /home dir.

go get -u github.com/golang/dep/cmd/dep
go get -u github.com/Masterminds/glide

# Finished installing GO packages into $GOPATH within /home dir.

