#!/bin/bash

set -v

# Installing Go packages into $GOPATH within /home dir.

if [ -n "$TORIFY" ]; then
    TORIFY=torify
fi

$TORIFY go get -u github.com/golang/dep/cmd/dep
$TORIFY go get -u github.com/Masterminds/glide
# FIXME: Current version I use is 1.8.4, get it from debian repo, when it be there.
$TORIFY go get -u github.com/gopasspw/gopass

# Personal Go tools.

$TORIFY go get -u github.com/nikolay-turpitko/elapsed
stow -vv --no-folding \
    -d "$(go env GOPATH)/src/github.com/nikolay-turpitko" \
    -t "$HOME/bin" --ignore=".*\..*" elapsed

$TORIFY go get -u github.com/nikolay-turpitko/x-newsbeuter-scripts/cmd/...

$TORIFY go get -d github.com/nikolay-turpitko/x-go-templator
(
    cd $GOPATH/src/github.com/nikolay-turpitko/x-go-templator

    glide i

    .build/install-icu4c.sh
    
    make install
)


# Finished installing Go packages into $GOPATH within /home dir.

