#!/bin/sh

cat << EOF

# Installing GO packages into $GOPATH within /home dir.

EOF

# golang packages
go get -u github.com/golang/dep/cmd/dep
go get -u github.com/Masterminds/glide

cat << EOF

# Finished installing GO packages into $GOPATH within /home dir.

EOF
