#!/bin/bash

# Entry point to post installation scripts.
# Executes all other executables within this folder.

# Use $TORIFY=torify env variable to torify downloads.

if [ -n "$TORIFY" ] || [ "$1" = "torify" ]; then
    export TORIFY=torify
fi

xargs -n 1 -a <(find -L ~/.postinst -executable -not -name postinst -type f | sort) /bin/bash
