#!/bin/bash

set -v

if ! command -v hp-setup; then
    exit 0
fi

# Installing HP printer.

# Note: cups web interface: http://localhost:631/

## >> Connect HP printer to USB (in case of VM - also selected in the virt-viewer)
## >> If something goes wrong, try to invoke commands manually

read -N 1 -p "Connect HP printer and press any key to continue"

# it's "not recommended" to run it under "sudo", but then it attempts to run "su" internally,
# and I prefer to leave root account locked (means cannot "su").

sudo hp-plugin -i

hp-setup -i

system-config-printer

# Finished installing HP printer.
