#!/bin/sh

set -v

# Setup custom alternatives (update-alternatives).

sudo update-alternatives --set x-www-browser /usr/bin/chromium

xdg-mime default evince.desktop application/pdf

# Finished setup custom alternatives (update-alternatives).
