#!/bin/sh

set -v

# Installing 3rd party debian packages, hosted outside of any repositories.

cat ~/.postinst/install-noncomplient | sudo /bin/bash

# Finished installing 3rd party debian packages, hosted outside of any repositories.
