#!/bin/sh

set -v

# VIM postinstallation tasks.

## Downloading spell files for VIM.

if [ -n "$TORIFY" ]; then
    TORIFY=torify
fi

mkdir -p "$HOME/.vim/spell"
$TORIFY /usr/bin/wget -NP "$HOME/.vim/spell" http://ftp.vim.org/vim/runtime/spell/ru.utf-8.spl
$TORIFY /usr/bin/wget -NP "$HOME/.vim/spell" http://ftp.vim.org/vim/runtime/spell/ru.utf-8.sug

## Updating go-vim binary dependencies, help tags.

vim +GoInstallBinaries +"helptags ALL" +q

# Finished VIM postinstallation tasks.
