#!/bin/bash

# see https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux-vpn-clients

VPN_SERVER_IP="$(gopass NET/vpn/vdsina.ru vpn-server-ip)"
VPN_IPSEC_PSK="$(gopass NET/vpn/vdsina.ru vpn-ipsec-psk)"
VPN_USER="$(gopass NET/vpn/vdsina.ru vpn-username)"
VPN_PASSWORD="$(gopass NET/vpn/vdsina.ru vpn-password)"

## Config strongswan

cat <<EOF | sudo tee /etc/ipsec.conf >/dev/null
# ipsec.conf - strongSwan IPsec configuration file

# basic configuration

config setup
  # strictcrlpolicy=yes
  # uniqueids = no

# Add connections here.

# Sample VPN connections

conn %default
  ikelifetime=60m
  keylife=20m
  rekeymargin=3m
  keyingtries=1
  keyexchange=ikev1
  authby=secret
  ike=aes128-sha1-modp1024,3des-sha1-modp1024!
  esp=aes128-sha1-modp1024,3des-sha1-modp1024!

conn myvpn
  keyexchange=ikev1
  left=%defaultroute
  auto=add
  authby=secret
  type=transport
  leftprotoport=17/1701
  rightprotoport=17/1701
  right=$VPN_SERVER_IP
EOF

cat <<EOF | sudo tee /etc/ipsec.secrets >/dev/null
: PSK "$VPN_IPSEC_PSK"
EOF

sudo chmod 600 /etc/ipsec.secrets

# For CentOS/RHEL & Fedora ONLY
sudo mv /etc/strongswan.d/ipsec.conf /etc/strongswan.d/ipsec.conf.old 2>/dev/null
sudo mv /etc/strongswan.d/ipsec.secrets /etc/strongswan.d/ipsec.secrets.old 2>/dev/null
sudo ln -s /etc/ipsec.conf /etc/strongswan.d/ipsec.conf
sudo ln -s /etc/ipsec.secrets /etc/strongswan.d/ipsec.secrets

## Config xl2tpd

cat <<EOF | sudo tee /etc/xl2tpd/xl2tpd.conf >/dev/null
[lac myvpn]
lns = $VPN_SERVER_IP
ppp debug = yes
pppoptfile = /etc/ppp/options.l2tpd.client
length bit = yes
EOF

cat <<EOF | sudo tee /etc/ppp/options.l2tpd.client >/dev/null
ipcp-accept-local
ipcp-accept-remote
refuse-eap
require-chap
noccp
noauth
mtu 1280
mru 1280
noipdefault
defaultroute
usepeerdns
connect-delay 5000
name $VPN_USER
password $VPN_PASSWORD
EOF

sudo chmod 600 /etc/ppp/options.l2tpd.client

