#!/bin/sh

# This is to install VirtualBox guest additions
# after Debian OS installation as a guest in the VirtualBox.
# Don't install it on your desktop.

sudo apt-get update
sudo apt-get upgrade
sudo m-a prepare

echo "Please go to the host's VirtualBox menu and click item"
echo "'Devices > Inserg Guest Additions CD image...'"
echo "Press <Enter> to continue..."
read x
sudo mount /media/cdrom
sudo sh /media/cdrom/VBoxLinuxAdditions.run
