#!/bin/sh

# unpack custom configs (probe cdrom and hd-media)
unpack_tars(){
    dir="$1"
    if [ -d "$dir" ]; then
        for f in "$dir"/*.tar; do
            tar -xf $f || echo "WARN: $f failed."
        done
    fi
}
unpack_tars "/media/cdrom/simple-cdd/cfg"
unpack_tars "/media/hd-media/simple-cdd/cfg"

dpkg-reconfigure console-setup
dpkg-reconfigure keyboard-configuration

wrkdir=$(pwd)
cd /etc/X11/
Xorg -configure
cd $wrkdir
