#!/bin/bash

set -eu

mkdir -p tmp
mkdir -p images

chmod 777 tmp
chmod 777 images

TAG="build-custom-debain-iso"
docker build --tag="${TAG}" .
docker run --rm -v $(pwd)/images:/build-iso/images -v $(pwd)/tmp:/build-iso/tmp "${TAG}"
